// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>

//! string-union-gen: Generate string conversion functions for ReScript polymorphic variants
//!
//! Scans ReScript files for `@stringUnion` annotated types and generates companion
//! files with toString/fromString functions.
//!
//! Example input:
//! ```rescript
//! @stringUnion
//! type status = [#pending | #active | #done]
//! ```
//!
//! Generated output (in `<filename>__strings.res`):
//! ```rescript
//! let statusToString = (v: status): string => switch v {
//!   | #pending => "pending"
//!   | #active => "active"
//!   | #done => "done"
//! }
//! let stringToStatus = (s: string): option<status> => switch s {
//!   | "pending" => Some(#pending)
//!   | "active" => Some(#active)
//!   | "done" => Some(#done)
//!   | _ => None
//! }
//! ```

use clap::Parser;
use colored::Colorize;
use regex::Regex;
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

#[derive(Parser, Debug)]
#[command(name = "string-union-gen")]
#[command(about = "Generate string conversion functions for ReScript polymorphic variants")]
#[command(version)]
struct Args {
    /// Source directory to scan
    #[arg(short, long, default_value = "src")]
    source: PathBuf,

    /// Output directory (defaults to same as source)
    #[arg(short, long)]
    output: Option<PathBuf>,

    /// Watch mode - regenerate on file changes
    #[arg(short, long)]
    watch: bool,

    /// Dry run - show what would be generated without writing
    #[arg(long)]
    dry_run: bool,

    /// Verbose output
    #[arg(short, long)]
    verbose: bool,

    /// Generated file suffix (default: __strings)
    #[arg(long, default_value = "__strings")]
    suffix: String,
}

/// A parsed polymorphic variant type with @stringUnion annotation
#[derive(Debug, Clone)]
struct StringUnion {
    /// The type name (e.g., "status")
    name: String,
    /// The variant tags (e.g., ["pending", "active", "done"])
    variants: Vec<VariantTag>,
    /// Line number in source file (used by diagnostics in verbose mode)
    #[allow(dead_code)]
    line: usize,
}

/// A single variant tag, possibly with a string override
#[derive(Debug, Clone)]
struct VariantTag {
    /// The ReScript tag name (e.g., "pending")
    tag: String,
    /// The string representation (may differ via @as)
    string_value: String,
}

/// Parse a ReScript file and extract all @stringUnion types
fn parse_file(content: &str) -> Vec<StringUnion> {
    let mut unions = Vec::new();

    // Regex to match @stringUnion followed by type definition
    // Handles both single-line and multi-line definitions
    let annotation_re =
        Regex::new(r"@stringUnion\s*\n?\s*type\s+(\w+)\s*=\s*\[([^\]]+)\]").unwrap();

    // Regex to extract individual variants, with optional @as annotation
    let variant_re = Regex::new(r#"(?:@as\("([^"]+)"\)\s*)?#(\w+)"#).unwrap();

    for caps in annotation_re.captures_iter(content) {
        let type_name = caps.get(1).unwrap().as_str().to_string();
        let variants_str = caps.get(2).unwrap().as_str();

        // Find approximate line number
        let match_start = caps.get(0).unwrap().start();
        let line = content[..match_start].lines().count();

        let mut variants = Vec::new();

        for var_caps in variant_re.captures_iter(variants_str) {
            let tag = var_caps.get(2).unwrap().as_str().to_string();
            let string_value = var_caps
                .get(1)
                .map(|m| m.as_str().to_string())
                .unwrap_or_else(|| tag.clone());

            variants.push(VariantTag { tag, string_value });
        }

        if !variants.is_empty() {
            unions.push(StringUnion {
                name: type_name,
                variants,
                line,
            });
        }
    }

    unions
}

/// Generate ReScript code for a StringUnion
fn generate_code(union: &StringUnion, source_module: &str) -> String {
    let type_name = &union.name;
    let type_ref = format!("{}.{}", source_module, type_name);

    // Capitalise first letter for function names
    let capitalised = {
        let mut chars = type_name.chars();
        match chars.next() {
            None => String::new(),
            Some(c) => c.to_uppercase().chain(chars).collect(),
        }
    };

    let mut code = String::new();

    // Header comment
    code.push_str(&format!(
        "// Generated by string-union-gen for {}.{}\n",
        source_module, type_name
    ));
    code.push_str("// Do not edit manually - regenerate with `string-union-gen`\n\n");

    // toString function
    code.push_str(&format!(
        "let {}ToString = (v: {}): string => switch v {{\n",
        type_name, type_ref
    ));
    for var in &union.variants {
        code.push_str(&format!("  | #{} => \"{}\"\n", var.tag, var.string_value));
    }
    code.push_str("}\n\n");

    // fromString function (returns option)
    code.push_str(&format!(
        "let stringTo{} = (s: string): option<{}> => switch s {{\n",
        capitalised, type_ref
    ));
    for var in &union.variants {
        code.push_str(&format!(
            "  | \"{}\" => Some(#{})\n",
            var.string_value, var.tag
        ));
    }
    code.push_str("  | _ => None\n");
    code.push_str("}\n\n");

    // fromStringExn function (throws on invalid)
    code.push_str(&format!(
        "let stringTo{}Exn = (s: string): {} => switch s {{\n",
        capitalised, type_ref
    ));
    for var in &union.variants {
        code.push_str(&format!("  | \"{}\" => #{}\n", var.string_value, var.tag));
    }
    code.push_str(&format!(
        "  | _ => Exn.raiseError(`Invalid {}: ${{s}}`)\n",
        type_name
    ));
    code.push_str("}\n\n");

    // allValues array
    code.push_str(&format!(
        "let all{}Values: array<{}> = [\n",
        capitalised, type_ref
    ));
    for var in &union.variants {
        code.push_str(&format!("  #{},\n", var.tag));
    }
    code.push_str("]\n\n");

    // allStrings array
    code.push_str(&format!(
        "let all{}Strings: array<string> = [\n",
        capitalised
    ));
    for var in &union.variants {
        code.push_str(&format!("  \"{}\",\n", var.string_value));
    }
    code.push_str("]\n");

    code
}

/// Process a single ReScript file
fn process_file(
    path: &Path,
    output_dir: &Path,
    suffix: &str,
    dry_run: bool,
    verbose: bool,
) -> Result<Option<PathBuf>, String> {
    let content = fs::read_to_string(path)
        .map_err(|e| format!("Failed to read {}: {}", path.display(), e))?;

    let unions = parse_file(&content);

    if unions.is_empty() {
        if verbose {
            println!("  {} No @stringUnion types found", "·".dimmed());
        }
        return Ok(None);
    }

    // Derive module name from filename
    let stem = path.file_stem().unwrap().to_str().unwrap();
    let module_name = {
        let mut chars = stem.chars();
        match chars.next() {
            None => String::new(),
            Some(c) => c.to_uppercase().chain(chars).collect(),
        }
    };

    // Generate output
    let mut output = String::new();
    output.push_str("// Auto-generated string union converters\n");
    output.push_str(&format!(
        "// Source: {}\n",
        path.file_name().unwrap().to_str().unwrap()
    ));
    output.push_str("// Regenerate with: string-union-gen\n\n");

    for union in &unions {
        output.push_str(&generate_code(union, &module_name));
    }

    // Determine output path
    let output_filename = format!("{}{}.res", stem, suffix);
    let output_path = output_dir.join(&output_filename);

    if dry_run {
        println!("{} {} would generate:", "DRY-RUN".yellow(), path.display());
        println!("  → {}", output_path.display());
        for union in &unions {
            println!(
                "    • {} ({} variants)",
                union.name.cyan(),
                union.variants.len()
            );
        }
        return Ok(Some(output_path));
    }

    // Write output
    fs::write(&output_path, &output)
        .map_err(|e| format!("Failed to write {}: {}", output_path.display(), e))?;

    println!(
        "{} {} → {}",
        "✓".green(),
        path.file_name().unwrap().to_str().unwrap(),
        output_filename
    );

    for union in &unions {
        if verbose {
            println!(
                "  {} {} ({} variants: {})",
                "·".dimmed(),
                union.name.cyan(),
                union.variants.len(),
                union
                    .variants
                    .iter()
                    .map(|v| format!("#{}", v.tag))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
    }

    Ok(Some(output_path))
}

/// Scan directory and process all .res files
fn process_directory(args: &Args) -> Result<(), String> {
    let output_dir = args.output.as_ref().unwrap_or(&args.source);

    println!(
        "{} Scanning {} for @stringUnion types...\n",
        "→".blue(),
        args.source.display()
    );

    let mut processed = 0;
    let mut generated = 0;

    for entry in WalkDir::new(&args.source)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .extension()
                .map(|ext| ext == "res")
                .unwrap_or(false)
                && !e.path().to_str().unwrap_or("").contains(&args.suffix)
        })
    {
        let path = entry.path();

        if args.verbose {
            println!("{} {}", "Scanning".dimmed(), path.display());
        }

        match process_file(path, output_dir, &args.suffix, args.dry_run, args.verbose) {
            Ok(Some(_)) => {
                generated += 1;
            }
            Ok(None) => {}
            Err(e) => {
                eprintln!("{} {}", "Error:".red(), e);
            }
        }

        processed += 1;
    }

    println!(
        "\n{} Processed {} files, generated {} outputs",
        "Done.".green(),
        processed,
        generated
    );

    Ok(())
}

fn main() {
    let args = Args::parse();

    if args.watch {
        println!(
            "{} Watch mode not yet implemented. Run without --watch for now.",
            "Warning:".yellow()
        );
        // TODO: Implement watch mode using notify crate
    }

    if let Err(e) = process_directory(&args) {
        eprintln!("{} {}", "Error:".red(), e);
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_simple_union() {
        let content = r#"
@stringUnion
type status = [#pending | #active | #done]
"#;
        let unions = parse_file(content);
        assert_eq!(unions.len(), 1);
        assert_eq!(unions[0].name, "status");
        assert_eq!(unions[0].variants.len(), 3);
        assert_eq!(unions[0].variants[0].tag, "pending");
    }

    #[test]
    fn test_parse_with_as_annotation() {
        let content = r#"
@stringUnion
type httpMethod = [@as("GET") #get | @as("POST") #post | @as("DELETE") #delete]
"#;
        let unions = parse_file(content);
        assert_eq!(unions.len(), 1);
        assert_eq!(unions[0].variants[0].tag, "get");
        assert_eq!(unions[0].variants[0].string_value, "GET");
        assert_eq!(unions[0].variants[1].string_value, "POST");
    }

    #[test]
    fn test_parse_multiline() {
        let content = r#"
@stringUnion
type role = [
  | #admin
  | #moderator
  | #user
  | #guest
]
"#;
        let unions = parse_file(content);
        assert_eq!(unions.len(), 1);
        assert_eq!(unions[0].variants.len(), 4);
    }

    #[test]
    fn test_multiple_unions() {
        let content = r#"
@stringUnion
type status = [#pending | #active]

type normalType = { name: string }

@stringUnion
type role = [#admin | #user]
"#;
        let unions = parse_file(content);
        assert_eq!(unions.len(), 2);
        assert_eq!(unions[0].name, "status");
        assert_eq!(unions[1].name, "role");
    }

    #[test]
    fn test_generate_code() {
        let union = StringUnion {
            name: "status".to_string(),
            variants: vec![
                VariantTag {
                    tag: "pending".to_string(),
                    string_value: "pending".to_string(),
                },
                VariantTag {
                    tag: "active".to_string(),
                    string_value: "active".to_string(),
                },
            ],
            line: 1,
        };

        let code = generate_code(&union, "MyModule");
        assert!(code.contains("statusToString"));
        assert!(code.contains("stringToStatus"));
        assert!(code.contains("stringToStatusExn"));
        assert!(code.contains("allStatusValues"));
        assert!(code.contains("MyModule.status"));
    }
}
